### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by River2017CN** [Litezero/ZeroClear-Manager#15]
1.During the "BDS Extraction" step, I have encountered an issue where the progress gets stuck at 40%. This problem has been consistently reproducible on multiple occasions.
2.I have encountered an issue where the loading animation exhibits tearing, specifically one-frame tearing. This problem occurs during the progress loading phase.
3.During the BDS download process, there is an issue where the displayed download speed is erroneously shown as 83655848Mb/s before the actual download progress begins and the real, valid download speed is calculated.

**Comment by 3R60Studio** [comment]
Thank you very much for submitting the issue, and we will do our best to address the issues you mentioned

**Comment by 3R60Studio** [comment]
The issue has been fixed in V4.2, thank you for your support
