### ISSUE TITLE
【优化】判断执行目录是不是桌面，避免在桌面拉屎

### ISSUE THREAD

**Issue by n15421** [Litezero/ZeroClear-Manager#38]
rt
只是一个简单的优化项
![EUQEM TNEUG@OEN{)(L 7@V](https://github.com/Litezero/ZeroClear-Manager/assets/119112174/2868b525-16dd-45c4-af64-72c774890440)

**Comment by n15421** [comment]
![_B$IM`~(~U@PQ6C%T32ANB9](https://github.com/Litezero/ZeroClear-Manager/assets/119112174/3ad07010-a8b1-4fe1-b456-844a11ba1161)
小小的建议

**Comment by LiteZero** [comment]
收到，谢谢
